"""Your message

Revision ID: a3e89a301a38
Revises: 2f0a3e863a91
Create Date: 2024-06-05 22:14:32.061176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e89a301a38'
down_revision = '2f0a3e863a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
